### ISSUE TITLE
Per node settings in configuration files is dangerous

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/simple_access_grants#12]
I can see the benefit of putting per content type into config files as well as the profile settings. But I think it's dangerous to put *per node* settings into config. Nodes themselves are not configuration, they're content and stored in the database. And they're easily deleted and created. So storing that in config would end up being really messy when trying to store config in version control and exporting/importing between environments.

**Comment by jlfranklin** [comment]
I agree.  Content may (and will) depend on config, but config should never depend on content.

**Comment by herbdool** [comment]
@Graham-72 can you clarify why you closed this issue? I took a quick look at your commit but doesn't look like it removes the reliance of config on content, which isn't great (as per above).

**Comment by Graham-72** [comment]
@herbdool perhaps I have misunderstood the issue but I thought that my error was to include node ids in config because these might be different if moving a site from one server to another.  Is there some other problem?

**Comment by jlfranklin** [comment]
Yes, removing the ability to do per-node grants is a major regression.  The problem wasn't _per node_ grants, it was _per node in config_.  Per node grants need to be saved in the database.

Do you want to reopen this issue or do you want to create a new one to address the regression?

**Comment by Graham-72** [comment]
@jlfranklin I understand, but I decided that as my aim is for a very simple access grants module, it does not need either the facility for per role settings or for per individual node settings, thereby removing some complexity from release 1.x-1.1.x. Do you think this is wrong?

**Comment by jlfranklin** [comment]
Per node was a feature I was using on a small set of production sites.  (It's a multisite setup.)  The regression meant a couple hours of work on my part to come up with a workaround.  These are small sites, so I was able to update the settings for the majority of the nodes and recreate the few remaining affected nodes as a different type. If these were hundred-node sites or larger, this could have been a big problem.

I really can't support the decision.

**Comment by herbdool** [comment]
I created a module that just does access control per content type and per role https://github.com/backdrop-contrib/content_view_access so sounds like there's still a need for one with per node settings like this one.

Do you want some help migrating the per node settings out of config and into the database?

**Comment by jlfranklin** [comment]
> I created a module that just does access control per content type and per role https://github.com/backdrop-contrib/content_view_access so sounds like there's still a need for one with per node settings like this one.

Drupal encouraged "joining forces" between modules with significant overlapping features. IMHO, this gave Drupal a much stronger library of modules.  Encouraging collaboration like that put more eyes on fewer lines of code, reducing bugs, and got people talking to each other, making the community stronger.  It also meant that looking for a module didn't overwhelm site builders with seventeen different options.

With the latest release, Simple Access Grants also does access control on a (content type x role) basis.  Perhaps your module and this one could merge and continue that tradition?

> Do you want some help migrating the per node settings out of config and into the database?

Thanks for the offer. I finished it last night.

I would like to see the per-node feature restored.  I would offer a PR, but I'm already overextended.

**Comment by herbdool** [comment]
My offer was to @graham-72 to help restore the per node in this module. If it gets restored there's still a justification for an even simpler node access like the one I created I think.

I didn't really want to create another module but I couldn't use this one at the time because I was unable to put config into version control.

**Comment by Graham-72** [comment]
@jlfranklin and @herbdool thank you both for your comments, and @herbdool for your offer of help. I need to think a bit longer about this. I originally produced this module because I needed some access control and the content_access module seemed very complicated, as did simple_access when I tried to port it. I very much agree with the sentiment of "joining forces" between modules with significant overlapping features, so perhaps we need to review what we now have. I am impressed by the simplicity of content_view_access but need time to think about whether it would meet the particular needs I had (and still have).

@herbdool, is putting config into version control still an issue and, if so, presumably this also applies to the settings for node types?
