### ISSUE TITLE
Warnings when adding access to a Content Type

### ISSUE THREAD

**Issue by jlfranklin** [backdrop-contrib/simple_access_grants#13]
Immediately after enabling the module, I edited the configuration of a Content Type to add some access controls and got the following warnings:

    Warning: Invalid argument supplied for foreach() in simple_access_grants_audit() (line 557 of modules/simple_access_grants/simple_access_grants.module).
    Warning: Invalid argument supplied for foreach() in simple_access_grants_audit() (line 622 of modules/simple_access_grants/simple_access_grants.module).

**Comment by Graham-72** [comment]
Thanks for reporting this. It needs a check that these settings exist.
