### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/simple_access_grants#8]
I was testing this for a project and when I set up a profile and then try to create content of that type from the site admin account, I get an error when I try to save:

`PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'gid' cannot be null: INSERT INTO {node_access} (nid, realm, gid, grant_view, grant_update, grant_delete) VALUES ...`

**Comment by Graham-72** [comment]
@laryn please can you give me a little more information about what you found? Specifically you say 'create content of that type' - what type of content was it?

**Comment by Graham-72** [comment]
'gid' requires a numerical value and for this the module uses a role ID which it stores in its config settings. This role ID needs to be added or deleted when a user role is added or removed from the site. The fix would seem to be to use hook_user_role_insert and hook_user_role_delete functions.

**Comment by laryn** [comment]
@Graham-72 I'll try to recreate and post better info. Sorry!

**Comment by Graham-72** [comment]
@laryn Thanks, though I think I have found the problem and have produced a fix. I am working on a couple of other things at the moment.

**Comment by laryn** [comment]
Okay, great.

**Comment by Graham-72** [comment]
@laryn I think I have now fixed this and other issues. If you get time please could you give it another try?
